# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AlloStand <- function(data, stand_attempt_max, tree_attempt_max, overlap_max, plot_length, quadrat_length, voxel_size, force, verbose) {
    .Call(`_Allostand_AlloStand`, data, stand_attempt_max, tree_attempt_max, overlap_max, plot_length, quadrat_length, voxel_size, force, verbose)
}

